### ISSUE TITLE
Epic : Affichage Consultation

### ISSUE THREAD

**Issue by MathieuBurnat** [CPNV-ES/PRW3_What-The-Dog#17]
## Description

L'objectif de cette story est de créer un rapport de consultation.

## Story

- [ ] Récupération des différentes données
- [ ] Affichage des données
- [ ] Print PDF
- [ ] Envoi par mail ?

## Definition of done
- [ ] La consultation suit [les étapes écrites dans le cahier des charges](https://demo.hedgedoc.org/s/RG7aoOLxT#Des-consultations-Mathieu-amp-Quentin-A-).
    - [ ] Les différentes données sont utilisables
    - [ ] L'envoi se fait via PDF
