### ISSUE TITLE
Epic : Création d'une consultation

### ISSUE THREAD

**Issue by MathieuBurnat** [CPNV-ES/PRW3_What-The-Dog#19]
## Description

L'objectif de cette story est de créer une consultation.

## Story

- [ ] Formulaire de création des données
    - [ ] Vérification des données
- [ ] Affichage d'une consultation une fois la création terminée
    - Plus d'info [ici](https://github.com/CPNV-ES/PRW3_What-The-Dog/issues/17).

## Definition of done
- [ ] Je peux créer une consultation et remplir [les champs suivants](https://demo.hedgedoc.org/s/RG7aoOLxT#Des-consultations-Mathieu-amp-Quentin-A-).
